### ISSUE TITLE
Compatibility with PrettyTables.jl

### ISSUE THREAD

**Issue by hellemo** [hellemo/SparseVariables.jl#15]
After example from Readme:
```julia
using PrettyTables
pretty_table(tab)
```

```
ERROR: MethodError: no method matching iterate(::Nothing)
Closest candidates are:
  iterate(::Union{LinRange, StepRangeLen}) at range.jl:872
  iterate(::Union{LinRange, StepRangeLen}, ::Integer) at range.jl:872
  iterate(::T) where T<:Union{Base.KeySet{<:Any, <:Dict}, Base.ValueIterator{<:Dict}} at dict.jl:712
```

Workaround via DataFrame:

```julia
pretty_table(DataFrame(tab))
```

```
┌────────┬───────┬─────────┐
│    car │  year │       y │
│ String │ Int64 │ Float64 │
├────────┼───────┼─────────┤
│    bmw │  2001 │     0.0 │
│   ford │  2001 │     0.0 │
│   ford │  2000 │     0.0 │
│    bmw │  2002 │     0.0 │
└────────┴───────┴─────────┘
```

**Comment by trulsf** [comment]
I have had a look into it and the problem seems to be that PrettyTables.jl assumes an ```iterate``` function that uses the row number as state. I have opened an issue to discuss it there: [https://github.com/ronisbr/PrettyTables.jl/issues/174](https://github.com/ronisbr/PrettyTables.jl/issues/174)

Not too hard to fix, but will then require either some internal storage of all indices or some cumbersome details. I would preferably see if there is hope for a change in PrettyTables.

**Comment by hellemo** [comment]
Works on PrettyTables#master
